[package]
name = "rust-playground"
version = "0.1.0"
authors = ["Matthew Knight <mattlknight@gmail.com>"]

[dependencies]
regex = "*"
lazy_static = "*"

[lib]
name = "mylib"
path = "src/lib.rs"

[[bin]]
name = "mybin"
path = "src/main.rs"
